### Inserer les routes ici ###
#### SITE BUNDLE #####

Accueil:
    method: GET
    url: /
    bundle: SiteBundle
    controller: HomeController
    action: Index

Arome025Ld:
    method: GET
    url: /modele/arome0025/LD/{parametre}
    bundle: SiteBundle
    controller: ModelController
    action: arome0025Ld

Arome025Hd:
    method: GET
    url: /modele/arome0025/HD/{parametre}
    bundle: SiteBundle
    controller: ModelController
    action: arome0025Hd


Arpege01EuropeHd:
    method: GET
    url: /modele/arpege01/HD/europe/{parametre}
    bundle: SiteBundle
    controller: ModelController
    action: arpege01EuropeHd

Arpege01FranceLd:
    method: GET
    url: /modele/arpege01/LD/france/{parametre}
    bundle: SiteBundle
    controller: ModelController
    action: arpege01FranceLd

ResultRecherche:
    method: POST
    url: /previsions/recherche
    bundle: SiteBundle
    controller: ForecastController
    action: search

AcceuilRecherche:
    method: GET
    url: /previsions/{model}
    bundle: SiteBundle
    controller: ForecastController
    action: index

detailForecast:
    method: GET
    url: /previsions/{model}/{idVille}/{slugVille}
    bundle: SiteBundle
    controller: ForecastController
    action: forecast

404:
    method: GET
    url: /notFound
    bundle: SiteBundle
    controller: ErrorController
    action: notFound


    